spring.application.name=corretor

spring.datasource.url=jdbc:postgresql://localhost:5432/corretor_db
spring.datasource.username=postgres
spring.datasource.password=123456
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=maycon-corretor-jwt-chave-super-segura-2026-mude-depois
jwt.expiration-ms=3600000
